### ISSUE TITLE
Deprecate/archive repository

### ISSUE THREAD

**Issue by docktermj** [Senzing/g2report#8]
`G2Report.py` was shipped the very early days - [Senzing 1.1.0](https://github.com/Senzing/g2-python/tree/1.1.0/g2/python),
but it doesn't seem to have been shipped since.

**Comment by jamietypovsky** [comment]
Per Butcher, we can delete this repository.  It is never used.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/g2report/pull/10
